[package]
name = "hdwallet"
version = "0.1.0"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
hmac = "0.10"
secp256k1 = { version = "0.19", features = ["recovery"] }
sha2 = "0.9"
sha3 = "0.9"
structopt = "0.3"
