[package]
name = "hdwallet"
version = "0.1.0"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
ethnum = "1"
hex = "0.4"
hmac = { version = "0.11", features = ["std"] }
pbkdf2 = { version = "0.8", default-features = false }
secp256k1 = { version = "0.20", features = ["recovery"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.9"
sha3 = "0.9"
structopt = "0.3"
unicode-normalization = "0.1"

[dev-dependencies]
hex-literal = "0.3"
maplit = "1"
