name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        rustup target add wasm32-wasi
        cargo build --release --target wasm32-wasi
    - name: Optimize
      run: |
        sudo apt-get update && sudo apt-get install binaryen
        wasm-opt target/wasm32-wasi/release/hdwallet.wasm -O4 -o target/hdwallet.wasm --strip-debug --strip-producers

    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${GITHUB_REF#refs/*/} -t ${GITHUB_REF#refs/*/} --generate-notes target/hdwallet.wasm
