name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy --locked --all-targets -- -D warnings
    - name: Test
      run: |
        cargo test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        rustup target add wasm32-wasi
        cargo build --target wasm32-wasi
