name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy --all-targets -- -D warnings
    - name: Test
      run: |
        cargo test

  wasm:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        curl -sL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-11/wasi-sdk_11.0_amd64.deb -o /tmp/wasi-sdk.deb
        sudo dpkg -i /tmp/wasi-sdk.deb
        rustup target add wasm32-wasi
        CC=/opt/wasi-sdk/bin/clang cargo build --release --target wasm32-wasi
    - name: Optimize
      run: |
        sudo apt-get update && sudo apt-get install binaryen wabt
        wasm2wat target/wasm32-wasi/release/hdwallet.wasm | grep -v '^\s*(export "rustsecp256k1_' > target/wasm32-wasi/release/hdwallet.exp.wat
        wat2wasm target/wasm32-wasi/release/hdwallet.exp.wat -o target/wasm32-wasi/release/hdwallet.exp.wasm
        wasm-opt target/wasm32-wasi/release/hdwallet.exp.wasm -O4 -o target/wasm32-wasi/release/hdwallet.opt.wasm --strip-debug
    - uses: actions/upload-artifact@v2
      with:
        name: hdwallet
        path: target/wasm32-wasi/release/hdwallet.opt.wasm
